quarkus.rest-client.apistax-api.url=https://api.apistax.io/v1/
quarkus.rest-client.apistax-api.connect-timeout=2000
quarkus.rest-client.apistax-api.read-timeout=5000

quarkus.rest-client.weather-forecast-api.url=https://api.open-meteo.com/v1
quarkus.rest-client.weather-forecast-api.connect-timeout=2000
quarkus.rest-client.weather-forecast-api.read-timeout=5000

apistax-api-key=${APISTAX_API_KEY:YOUR_API_KEY}

# CORS for local Angular development
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.headers=Authorization,Content-Type,Accept,Origin,X-Requested-With
quarkus.http.cors.exposed-headers=Content-Type
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.access-control-allow-credentials=true